[tox]
minversion = 4.4.3
envlist = py{310,311,312,313}, lint, coverage, docs
isolated_build = True

[testenv]
package = wheel
wheel_build_env = .pkg
parallel_show_output = True
extras =
  test
commands =
  pytest {posargs}

[testenv:style]
extras =
  style
commands =
  ruff format qiskit_mitigation/ docs/ test/
  ruff check --fix qiskit_mitigation/ docs/ test/
  nbqa ruff --fix docs/

[testenv:lint]
image-tester-commit = 7ae965ccf21c39e5170334ec7f4882756883860a
deps = 
  git+https://github.com/Qiskit/documentation.git@{[testenv:lint]image-tester-commit}\#egg=sphinx-alt-text-validator&subdirectory=scripts/image-tester
basepython = python3.10
extras =
  lint
commands =
  ruff format --check qiskit_mitigation/ docs/ test/
  ruff check qiskit_mitigation/ docs/ test/
  ruff check --preview --select CPY001 --exclude "*.ipynb" qiskit_mitigation/ test/
  nbqa ruff docs/
  mypy qiskit_mitigation/
  pylint -rn qiskit_mitigation/ test/
  sphinx-alt-text-validator -f qiskit_mitigation
  nbqa pylint -rn docs/

[testenv:coverage]
basepython = python3.10
deps =
  coverage>=7.4.1
extras =
  test
commands =
  pytest --doctest-modules --cov=qiskit_mitigation/

[testenv:docs]
basepython = python3.10
extras =
  docs
commands =
  sphinx-build -j auto -W -T --keep-going -b html {posargs} {toxinidir}/docs/ {toxinidir}/docs/_build/html
passenv =
  CI
  GITHUB_BASE_REF
  GITHUB_REF_NAME

[testenv:docs-clean]
skip_install = true
allowlist_externals =
  rm
commands =
  rm -rf {toxinidir}/docs/stubs/ {toxinidir}/docs/_build/
